### PR TITLE
fix VoiceOver for Selected PagingTitleCell

### PR DESCRIPTION
**Pull request by RyoAbe**
Fixed speak correctly when VoiceOver was enabled.
- fix speak for selected PagingTitleCell

### CODE REVIEW

**Comment by RyoAbe** [comment]
@rechsteiner Please review this pull request🙏

**Comment by rechsteiner** [comment]
Hey @RyoAbe! Thank you for fixing this. One this that I have noticed when setting `isAccessiblityElement` on the cell and not the content view is that UI tests throw an error when recording. Can you update it to set everything on the content view instead?

```Swift
contentView.isAccessibilityElement = true
contentView.accessibilityLabel = viewModel?.title
contentView.accessibilityTraits = viewModel?.selected ?? false ? .selected : .none
```

**Comment by RyoAbe** [comment]
@rechsteiner I've revised the PR based on your comments, can you please review it again?

**Comment by rechsteiner** [comment]
Looks great, thanks for doing this!

**Pull request merged**
