### PR TITLE
XCode 10/ Swift 4.2 support

### PR DESCRIPTION
**Pull request by QuestofIranon**
I converted and corrected issues in the main library so it will work in Swift 4.2

However, I disabled the unit tests since they had dependencies that haven't been updated yet.

### CODE REVIEW

**Comment by prsolucoes** [comment]
Merge!!!

**Comment by rechsteiner** [comment]
Hi @QuestofIranon! Sorry for the delay (been on vacation the last weeks). Thank you so much for fixing this 🙌 It looks like Quick v1.3 has been released with support for Swift 4.2. Could you update the dependencies and enable the tests again?

**Comment by QuestofIranon** [comment]
Hi @rechsteiner I will do this over the next few days.

**Comment by rechsteiner** [comment]
I realized that we needed to make some more changes in order to continue to support previous version of Swift, so I ended up converting it myself (#228). Thank you again for the contribution, I really appreciate it 🙂

**Pull request closed without merging**
