### PR TITLE
Update UIFont weight

### PR DESCRIPTION
**Pull request by MamdouhRElNakeeb**

### CODE REVIEW

**Comment by rechsteiner** [comment]
Hi @MamdouhRElNakeeb! This change doesn't compile when using with Swift 4. Could you provide some motivation behind this change? Are you seeing any issues with using `UIFont.Weight.medium` on older versions of iOS?

**Comment by rechsteiner** [comment]
@MamdouhRElNakeeb could you provide some more details on this?

**Comment by MamdouhRElNakeeb** [comment]
Sorry for confusing
In Swift 4.0: UIFont.Weight.medium
In Swift 3.2: UIFontWeightMedium

**Comment by rechsteiner** [comment]
Parchment is only supporting the latest version of Swift. The change you are suggesting won't compile when using Swift 4. If you want to use Parchment with Swift 3.2 you have to use an older version.

**Comment by rechsteiner** [comment]
@MamdouhRElNakeeb @bizibizi fixed in #190 now 🙂

**Pull request closed without merging**
